// Traductions du composant 4_SCRUBBER_TourLavage.
// fr + en fournis ; les autres langues retombent sur fr via la logique t()
// du composant (à fusionner dans SCRUBBER_traduction.jsx si préféré).
export const tlTranslations = {
  fr: {
    TL_legend_input: 'saisie',
    TL_legend_calc: 'calculé',
    TL_legend_warn: 'hors plage',
    TL_reload_from_flow: 'Recharger depuis le flux amont',
    TL_err_invalid_composition: 'Composition des fumées invalide : débit volumique total ou sec nul.',

    TL_section_inlet: 'Fumées en entrée (sortie quench)',
    TL_section_column: 'Colonne — choix & réactif',
    TL_section_packing: 'Caractéristiques du garnissage',
    TL_section_subcooling: "Utilisation d'un sous-refroidissement",
    TL_section_demister: 'Dévésiculeur',
    TL_section_verifications: 'Engorgement & vérifications',
    TL_section_absorption: "Partie absorption",
    TL_section_outlet: 'Fumées en sortie',
    TL_section_water_reagent: 'Bilans eau & soude',

    TL_flow_CO2: 'Débit CO₂',
    TL_flow_H2O: 'Débit H₂O vapeur',
    TL_flow_N2: 'Débit N₂',
    TL_flow_O2: 'Débit O₂',
    TL_flow_SO2: 'Débit SO₂',
    TL_flow_HCl: 'Débit HCl',
    TL_flow_dust: 'Poussières',
    TL_temperature: 'Température',
    TL_pressure_drop_upstream: 'Dépression totale',
    TL_total_mass_flow: 'Débit massique total',
    TL_total_vol_flow: 'Débit volumique total',
    TL_o2_dry: 'O₂ sur sec',
    TL_so2_dry_11: 'SO₂ (sec, 11 % O₂)',
    TL_hcl_dry_11: 'HCl (sec, 11 % O₂)',

    TL_selected_diameter: 'Diamètre retenu',
    TL_spray_flow: "Débit du liquide d'arrosage",
    TL_naoh_pct: 'Soude — % massique NaOH',
    TL_so2_salts: 'Sels de SO₂ dans la purge',
    TL_target_so2: 'Objectif SO₂ sortie',
    TL_target_hcl: 'Objectif HCl sortie',

    TL_packing_type: 'Type (perte de charge)',
    TL_other: 'Autres',
    TL_sat_height_coef: 'Coef. hauteur saturation',
    TL_packing_factor: 'Facteur de garnissage',
    TL_specific_area: 'Surface volumique',
    TL_packing_size: 'Diamètre / dimension',
    TL_critical_tension: 'Tension superf. matériau',

    TL_use_subcooling: 'Condenseur en tête',
    TL_yes: 'Oui',
    TL_no: 'Non',
    TL_cooling_liquid_temp: "Température d'entrée du liquide",
    TL_condenser_outlet_temp: 'Température sortie condenseur',
    TL_condenser_height: 'Hauteur',
    TL_condensate_flow: 'Débit condensat',
    TL_cooling_water_flow: 'Débit eau de refroid.',
    TL_liquid_outlet_temp: 'Température sortie liquide',
    TL_condenser_duty: 'Puissance échangée',

    TL_demister_thickness: 'Épaisseur',
    TL_demister_diameter: 'Diamètre retenu (arrondi 0,5)',
    TL_demister_velocity: 'Vitesse retenue',
    TL_demister_dp: 'Perte de charge',

    TL_flooding_flux: "Flux d'engorgement",
    TL_real_flux: 'Flux réel (70 %)',
    TL_computed_diameter: 'Diamètre calculé',
    TL_wetting_rate: 'Taux de mouillage',
    TL_ratio_check: 'Rapport D colonne / d garnissage',
    TL_flooding_rate: "Taux d'engorgement",

    TL_packing_height_so2: 'Hauteur garnissage SO₂',
    TL_packing_height_hcl: 'Hauteur garnissage HCl',
    TL_packing_height_total: 'Hauteur retenue',
    TL_packing_dp: 'Perte de charge garnissage',
    TL_packing_dp_per_m: 'Perte de charge / hauteur',
    TL_hut_so2: 'HUT SO₂',
    TL_nut_so2: 'NUT SO₂',
    TL_hut_hcl: 'HUT HCl',
    TL_nut_hcl: 'NUT HCl',
    TL_wetted_area: 'Surface mouillée (Onda)',

    TL_efficiency_so2: 'Efficacité SO₂',
    TL_efficiency_hcl: 'Efficacité HCl',

    TL_makeup_water: "Débit eau d'appoint",
    TL_so2_purge: 'Débit purge de SO₂',
    TL_total_purge: 'Purge totale colonne',
    TL_naoh_conc: 'Concentration solution',
    TL_naoh_nominal: 'Quantité de NaOH (nominal)',
    TL_naoh_nominal_vol: 'Débit volumique (nominal)',
    TL_naoh_maxi: 'Quantité de NaOH (maxi)',

    // Rapport
    TL_report_section: 'Tour de lavage (voie humide)',
    TL_report_performances: 'Performances',
    TL_report_design: 'Dimensionnement',
    TL_report_balances: 'Bilans eau & réactif',
    TL_report_condenser: 'Condenseur',
  },
  en: {
    TL_legend_input: 'input',
    TL_legend_calc: 'calculated',
    TL_legend_warn: 'out of range',
    TL_reload_from_flow: 'Reload from upstream flow',
    TL_err_invalid_composition: 'Invalid flue gas composition: total or dry volume flow is zero.',

    TL_section_inlet: 'Inlet flue gas (quench outlet)',
    TL_section_column: 'Column — selection & reagent',
    TL_section_packing: 'Packing characteristics',
    TL_section_subcooling: 'Sub-cooling (condenser)',
    TL_section_demister: 'Demister',
    TL_section_verifications: 'Flooding & checks',
    TL_section_absorption: 'Absorption section',
    TL_section_outlet: 'Outlet flue gas',
    TL_section_water_reagent: 'Water & caustic balances',

    TL_flow_CO2: 'CO₂ flow',
    TL_flow_H2O: 'H₂O vapour flow',
    TL_flow_N2: 'N₂ flow',
    TL_flow_O2: 'O₂ flow',
    TL_flow_SO2: 'SO₂ flow',
    TL_flow_HCl: 'HCl flow',
    TL_flow_dust: 'Dust',
    TL_temperature: 'Temperature',
    TL_pressure_drop_upstream: 'Total draft',
    TL_total_mass_flow: 'Total mass flow',
    TL_total_vol_flow: 'Total volume flow',
    TL_o2_dry: 'O₂ dry basis',
    TL_so2_dry_11: 'SO₂ (dry, 11 % O₂)',
    TL_hcl_dry_11: 'HCl (dry, 11 % O₂)',

    TL_selected_diameter: 'Selected diameter',
    TL_spray_flow: 'Spray liquid flow',
    TL_naoh_pct: 'Caustic — NaOH mass %',
    TL_so2_salts: 'SO₂ salts in blowdown',
    TL_target_so2: 'SO₂ outlet target',
    TL_target_hcl: 'HCl outlet target',

    TL_packing_type: 'Type (pressure drop)',
    TL_other: 'Other',
    TL_sat_height_coef: 'Saturation height coef.',
    TL_packing_factor: 'Packing factor',
    TL_specific_area: 'Specific area',
    TL_packing_size: 'Diameter / size',
    TL_critical_tension: 'Critical surface tension',

    TL_use_subcooling: 'Top condenser',
    TL_yes: 'Yes',
    TL_no: 'No',
    TL_cooling_liquid_temp: 'Cooling liquid inlet temp.',
    TL_condenser_outlet_temp: 'Condenser outlet temp.',
    TL_condenser_height: 'Height',
    TL_condensate_flow: 'Condensate flow',
    TL_cooling_water_flow: 'Cooling water flow',
    TL_liquid_outlet_temp: 'Liquid outlet temp.',
    TL_condenser_duty: 'Exchanged duty',

    TL_demister_thickness: 'Thickness',
    TL_demister_diameter: 'Selected diameter (0.5 rounding)',
    TL_demister_velocity: 'Selected velocity',
    TL_demister_dp: 'Pressure drop',

    TL_flooding_flux: 'Flooding flux',
    TL_real_flux: 'Actual flux (70 %)',
    TL_computed_diameter: 'Computed diameter',
    TL_wetting_rate: 'Wetting rate',
    TL_ratio_check: 'Column D / packing d ratio',
    TL_flooding_rate: 'Flooding rate',

    TL_packing_height_so2: 'SO₂ packing height',
    TL_packing_height_hcl: 'HCl packing height',
    TL_packing_height_total: 'Selected height',
    TL_packing_dp: 'Packing pressure drop',
    TL_packing_dp_per_m: 'Pressure drop / height',
    TL_hut_so2: 'HTU SO₂',
    TL_nut_so2: 'NTU SO₂',
    TL_hut_hcl: 'HTU HCl',
    TL_nut_hcl: 'NTU HCl',
    TL_wetted_area: 'Wetted area (Onda)',

    TL_efficiency_so2: 'SO₂ efficiency',
    TL_efficiency_hcl: 'HCl efficiency',

    TL_makeup_water: 'Make-up water flow',
    TL_so2_purge: 'SO₂ blowdown flow',
    TL_total_purge: 'Total column blowdown',
    TL_naoh_conc: 'Solution concentration',
    TL_naoh_nominal: 'NaOH quantity (nominal)',
    TL_naoh_nominal_vol: 'Volume flow (nominal)',
    TL_naoh_maxi: 'NaOH quantity (max)',

    // Report
    TL_report_section: 'Wet scrubbing tower',
    TL_report_performances: 'Performances',
    TL_report_design: 'Design',
    TL_report_balances: 'Water & reagent balances',
    TL_report_condenser: 'Condenser',
  },
};
