const authTranslations = {
  fr: {
    restrictedAccess: 'Accès restreint',
    enterEmail: 'Entrez votre email',
    verify: 'Vérifier',
    accessDenied: 'Accès refusé : adresse e-mail non autorisée ou expirée.',
    noAccess: "Vous n'avez pas encore d'accès ?",
    requestAccess: 'Demander un accès',
    managementTitle: 'Gestion des accès utilisateurs',
    gsheetInfo: "Les accès sont gérés via Google Sheets. Ajoute ou supprime des emails directement dans le sheet — les changements prennent effet au prochain chargement de l'application.",
    openGsheet: 'Ouvrir Google Sheet',
    authorizedUsers: 'Utilisateurs autorisés',
    colEmail: 'Email',
    colValidUntil: "Valide jusqu'au",
    colSource: 'Source',
    srcPermanent: 'Permanent',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Temporaire',
    close: 'Fermer',
    requestTitle: 'Demander un accès',
    requestDesc: "Remplissez ce formulaire pour demander un accès à l'application. Un email sera automatiquement préparé pour l'administrateur.",
    yourEmail: 'Votre adresse email *',
    emailPlaceholder: 'votre.email@exemple.com',
    messageLabel: 'Message (optionnel)',
    messagePlaceholder: "Indiquez la raison de votre demande d'accès...",
    cancel: 'Annuler',
    send: 'Envoyer la demande',
    validEmail: 'Veuillez entrer une adresse email valide.',
    requestPrepared: "Votre demande d'accès a été préparée. Veuillez envoyer l'email qui vient de s'ouvrir dans votre client email.",
    emailErrorPrefix: "Impossible d'ouvrir votre client email. Veuillez contacter ",
    emailErrorSuffix: ' manuellement.',
    mailSubject: "Demande d'accès à l'application",
    mailGreeting: 'Bonjour,',
    mailBody1: "Je souhaiterais obtenir un accès à l'application.",
    mailMyEmail: 'Mon adresse email :',
    mailMessage: 'Message :',
    mailNoMessage: 'Aucun message supplémentaire',
    mailThanks: 'Merci de bien vouloir étudier ma demande.',
    mailRegards: 'Cordialement',
  },
  en: {
    restrictedAccess: 'Restricted Access',
    enterEmail: 'Enter your email',
    verify: 'Verify',
    accessDenied: 'Access denied: unauthorized or expired email address.',
    noAccess: "Don't have access yet?",
    requestAccess: 'Request Access',
    managementTitle: 'User Access Management',
    gsheetInfo: 'Access is managed via Google Sheets. Add or remove emails directly in the sheet — changes take effect on the next app reload.',
    openGsheet: 'Open Google Sheet',
    authorizedUsers: 'Authorized Users',
    colEmail: 'Email',
    colValidUntil: 'Valid Until',
    colSource: 'Source',
    srcPermanent: 'Permanent',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Temporary',
    close: 'Close',
    requestTitle: 'Request Access',
    requestDesc: 'Fill out this form to request application access. An email will be automatically prepared for the administrator.',
    yourEmail: 'Your email address *',
    emailPlaceholder: 'your.email@example.com',
    messageLabel: 'Message (optional)',
    messagePlaceholder: 'Indicate the reason for your access request...',
    cancel: 'Cancel',
    send: 'Send Request',
    validEmail: 'Please enter a valid email address.',
    requestPrepared: 'Your access request has been prepared. Please send the email that just opened in your email client.',
    emailErrorPrefix: 'Unable to open your email client. Please contact ',
    emailErrorSuffix: ' manually.',
    mailSubject: 'Application Access Request',
    mailGreeting: 'Hello,',
    mailBody1: 'I would like to request access to the application.',
    mailMyEmail: 'My email address:',
    mailMessage: 'Message:',
    mailNoMessage: 'No additional message',
    mailThanks: 'Thank you for considering my request.',
    mailRegards: 'Best regards',
  },
  es: {
    restrictedAccess: 'Acceso Restringido',
    enterEmail: 'Ingrese su email',
    verify: 'Verificar',
    accessDenied: 'Acceso denegado: dirección de email no autorizada o expirada.',
    noAccess: '¿Aún no tienes acceso?',
    requestAccess: 'Solicitar Acceso',
    managementTitle: 'Gestión de Acceso de Usuarios',
    gsheetInfo: 'Los accesos se gestionan vía Google Sheets. Agrega o elimina emails directamente en el sheet — los cambios tienen efecto en la próxima recarga de la app.',
    openGsheet: 'Abrir Google Sheet',
    authorizedUsers: 'Usuarios Autorizados',
    colEmail: 'Email',
    colValidUntil: 'Válido Hasta',
    colSource: 'Fuente',
    srcPermanent: 'Permanente',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Temporal',
    close: 'Cerrar',
    requestTitle: 'Solicitar Acceso',
    requestDesc: 'Complete este formulario para solicitar acceso a la aplicación. Se preparará automáticamente un email para el administrador.',
    yourEmail: 'Su dirección de email *',
    emailPlaceholder: 'su.email@ejemplo.com',
    messageLabel: 'Mensaje (opcional)',
    messagePlaceholder: 'Indique la razón de su solicitud de acceso...',
    cancel: 'Cancelar',
    send: 'Enviar Solicitud',
    validEmail: 'Por favor ingrese una dirección de email válida.',
    requestPrepared: 'Su solicitud de acceso ha sido preparada. Por favor envíe el email que se acaba de abrir en su cliente de email.',
    emailErrorPrefix: 'No se pudo abrir su cliente de email. Por favor contacte a ',
    emailErrorSuffix: ' manualmente.',
    mailSubject: 'Solicitud de acceso a la aplicación',
    mailGreeting: 'Hola,',
    mailBody1: 'Me gustaría obtener acceso a la aplicación.',
    mailMyEmail: 'Mi dirección de email:',
    mailMessage: 'Mensaje:',
    mailNoMessage: 'Sin mensaje adicional',
    mailThanks: 'Gracias por considerar mi solicitud.',
    mailRegards: 'Atentamente',
  },
  de: {
    restrictedAccess: 'Eingeschränkter Zugriff',
    enterEmail: 'E-Mail eingeben',
    verify: 'Überprüfen',
    accessDenied: 'Zugriff verweigert: nicht autorisierte oder abgelaufene E-Mail-Adresse.',
    noAccess: 'Noch keinen Zugang?',
    requestAccess: 'Zugang anfordern',
    managementTitle: 'Benutzerzugriffsverwaltung',
    gsheetInfo: 'Der Zugriff wird über Google Sheets verwaltet. Fügen Sie E-Mails direkt im Sheet hinzu oder entfernen Sie sie — Änderungen werden beim nächsten App-Laden wirksam.',
    openGsheet: 'Google Sheet öffnen',
    authorizedUsers: 'Autorisierte Benutzer',
    colEmail: 'E-Mail',
    colValidUntil: 'Gültig bis',
    colSource: 'Quelle',
    srcPermanent: 'Dauerhaft',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Temporär',
    close: 'Schließen',
    requestTitle: 'Zugang anfordern',
    requestDesc: 'Füllen Sie dieses Formular aus, um Zugang zur Anwendung anzufordern. Eine E-Mail wird automatisch für den Administrator vorbereitet.',
    yourEmail: 'Ihre E-Mail-Adresse *',
    emailPlaceholder: 'ihre.email@beispiel.com',
    messageLabel: 'Nachricht (optional)',
    messagePlaceholder: 'Geben Sie den Grund Ihrer Zugriffsanfrage an...',
    cancel: 'Abbrechen',
    send: 'Anfrage senden',
    validEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    requestPrepared: 'Ihre Zugriffsanfrage wurde vorbereitet. Bitte senden Sie die E-Mail, die gerade in Ihrem E-Mail-Client geöffnet wurde.',
    emailErrorPrefix: 'Ihr E-Mail-Client konnte nicht geöffnet werden. Bitte kontaktieren Sie ',
    emailErrorSuffix: ' manuell.',
    mailSubject: 'Zugriffsanfrage für die Anwendung',
    mailGreeting: 'Guten Tag,',
    mailBody1: 'Ich möchte Zugang zur Anwendung beantragen.',
    mailMyEmail: 'Meine E-Mail-Adresse:',
    mailMessage: 'Nachricht:',
    mailNoMessage: 'Keine zusätzliche Nachricht',
    mailThanks: 'Vielen Dank für die Bearbeitung meiner Anfrage.',
    mailRegards: 'Mit freundlichen Grüßen',
  },
  it: {
    restrictedAccess: 'Accesso Limitato',
    enterEmail: 'Inserisci la tua email',
    verify: 'Verifica',
    accessDenied: 'Accesso negato: indirizzo email non autorizzato o scaduto.',
    noAccess: 'Non hai ancora accesso?',
    requestAccess: 'Richiedi Accesso',
    managementTitle: 'Gestione Accesso Utenti',
    gsheetInfo: "L'accesso è gestito tramite Google Sheets. Aggiungi o rimuovi email direttamente nel foglio — le modifiche avranno effetto al prossimo caricamento dell'app.",
    openGsheet: 'Apri Google Sheet',
    authorizedUsers: 'Utenti Autorizzati',
    colEmail: 'Email',
    colValidUntil: 'Valido Fino Al',
    colSource: 'Fonte',
    srcPermanent: 'Permanente',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Temporaneo',
    close: 'Chiudi',
    requestTitle: 'Richiedi Accesso',
    requestDesc: "Compila questo modulo per richiedere l'accesso all'applicazione. Un'email verrà preparata automaticamente per l'amministratore.",
    yourEmail: 'Il tuo indirizzo email *',
    emailPlaceholder: 'tua.email@esempio.com',
    messageLabel: 'Messaggio (opzionale)',
    messagePlaceholder: "Indica il motivo della tua richiesta di accesso...",
    cancel: 'Annulla',
    send: 'Invia Richiesta',
    validEmail: 'Inserisci un indirizzo email valido.',
    requestPrepared: "La tua richiesta di accesso è stata preparata. Invia l'email che si è appena aperta nel tuo client di posta.",
    emailErrorPrefix: 'Impossibile aprire il client email. Contatta ',
    emailErrorSuffix: ' manualmente.',
    mailSubject: "Richiesta di accesso all'applicazione",
    mailGreeting: 'Salve,',
    mailBody1: "Vorrei ottenere l'accesso all'applicazione.",
    mailMyEmail: 'Il mio indirizzo email:',
    mailMessage: 'Messaggio:',
    mailNoMessage: 'Nessun messaggio aggiuntivo',
    mailThanks: 'Grazie per aver considerato la mia richiesta.',
    mailRegards: 'Cordiali saluti',
  },
  pt: {
    restrictedAccess: 'Acesso Restrito',
    enterEmail: 'Digite seu email',
    verify: 'Verificar',
    accessDenied: 'Acesso negado: endereço de email não autorizado ou expirado.',
    noAccess: 'Ainda não tem acesso?',
    requestAccess: 'Solicitar Acesso',
    managementTitle: 'Gerenciamento de Acesso de Usuários',
    gsheetInfo: 'O acesso é gerenciado via Google Sheets. Adicione ou remova emails diretamente na planilha — as alterações têm efeito no próximo carregamento do app.',
    openGsheet: 'Abrir Google Sheet',
    authorizedUsers: 'Usuários Autorizados',
    colEmail: 'Email',
    colValidUntil: 'Válido Até',
    colSource: 'Fonte',
    srcPermanent: 'Permanente',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Temporário',
    close: 'Fechar',
    requestTitle: 'Solicitar Acesso',
    requestDesc: 'Preencha este formulário para solicitar acesso ao aplicativo. Um email será preparado automaticamente para o administrador.',
    yourEmail: 'Seu endereço de email *',
    emailPlaceholder: 'seu.email@exemplo.com',
    messageLabel: 'Mensagem (opcional)',
    messagePlaceholder: 'Indique o motivo da sua solicitação de acesso...',
    cancel: 'Cancelar',
    send: 'Enviar Solicitação',
    validEmail: 'Por favor, insira um endereço de email válido.',
    requestPrepared: 'Sua solicitação de acesso foi preparada. Envie o email que acabou de abrir no seu cliente de email.',
    emailErrorPrefix: 'Não foi possível abrir seu cliente de email. Por favor, contate ',
    emailErrorSuffix: ' manualmente.',
    mailSubject: 'Solicitação de acesso ao aplicativo',
    mailGreeting: 'Olá,',
    mailBody1: 'Gostaria de obter acesso ao aplicativo.',
    mailMyEmail: 'Meu endereço de email:',
    mailMessage: 'Mensagem:',
    mailNoMessage: 'Sem mensagem adicional',
    mailThanks: 'Obrigado por considerar minha solicitação.',
    mailRegards: 'Atenciosamente',
  },
  ar: {
    restrictedAccess: 'وصول مقيّد',
    enterEmail: 'أدخل بريدك الإلكتروني',
    verify: 'تحقق',
    accessDenied: 'تم رفض الوصول: عنوان البريد الإلكتروني غير مصرح به أو منتهي الصلاحية.',
    noAccess: 'ليس لديك وصول بعد؟',
    requestAccess: 'طلب الوصول',
    managementTitle: 'إدارة وصول المستخدمين',
    gsheetInfo: 'يُدار الوصول عبر Google Sheets. أضف أو احذف البريد الإلكتروني مباشرة في الجدول — تسري التغييرات عند إعادة تحميل التطبيق.',
    openGsheet: 'فتح Google Sheet',
    authorizedUsers: 'المستخدمون المصرح لهم',
    colEmail: 'البريد الإلكتروني',
    colValidUntil: 'صالح حتى',
    colSource: 'المصدر',
    srcPermanent: 'دائم',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'مؤقت',
    close: 'إغلاق',
    requestTitle: 'طلب الوصول',
    requestDesc: 'املأ هذا النموذج لطلب الوصول إلى التطبيق. سيتم تجهيز بريد إلكتروني تلقائياً للمسؤول.',
    yourEmail: 'عنوان بريدك الإلكتروني *',
    emailPlaceholder: 'بريدك@مثال.com',
    messageLabel: 'رسالة (اختياري)',
    messagePlaceholder: 'أدخل سبب طلب الوصول...',
    cancel: 'إلغاء',
    send: 'إرسال الطلب',
    validEmail: 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
    requestPrepared: 'تم تجهيز طلب الوصول. يرجى إرسال البريد الإلكتروني الذي تم فتحه في تطبيق البريد.',
    emailErrorPrefix: 'تعذر فتح تطبيق البريد. يرجى التواصل مع ',
    emailErrorSuffix: ' يدوياً.',
    mailSubject: 'طلب الوصول إلى التطبيق',
    mailGreeting: 'مرحباً،',
    mailBody1: 'أود الحصول على إذن للوصول إلى التطبيق.',
    mailMyEmail: 'عنوان بريدي الإلكتروني:',
    mailMessage: 'رسالة:',
    mailNoMessage: 'لا توجد رسالة إضافية',
    mailThanks: 'شكراً لدراسة طلبي.',
    mailRegards: 'مع التقدير',
  },
  ru: {
    restrictedAccess: 'Ограниченный доступ',
    enterEmail: 'Введите ваш email',
    verify: 'Проверить',
    accessDenied: 'Доступ запрещён: адрес электронной почты не авторизован или устарел.',
    noAccess: 'Ещё нет доступа?',
    requestAccess: 'Запросить доступ',
    managementTitle: 'Управление доступом пользователей',
    gsheetInfo: 'Доступ управляется через Google Sheets. Добавляйте или удаляйте email прямо в таблице — изменения вступят в силу при следующей загрузке приложения.',
    openGsheet: 'Открыть Google Sheet',
    authorizedUsers: 'Авторизованные пользователи',
    colEmail: 'Email',
    colValidUntil: 'Действует до',
    colSource: 'Источник',
    srcPermanent: 'Постоянный',
    srcGsheet: 'Google Sheet',
    srcTemporary: 'Временный',
    close: 'Закрыть',
    requestTitle: 'Запросить доступ',
    requestDesc: 'Заполните эту форму для запроса доступа к приложению. Email для администратора будет подготовлен автоматически.',
    yourEmail: 'Ваш адрес электронной почты *',
    emailPlaceholder: 'ваш.email@пример.com',
    messageLabel: 'Сообщение (необязательно)',
    messagePlaceholder: 'Укажите причину запроса доступа...',
    cancel: 'Отмена',
    send: 'Отправить запрос',
    validEmail: 'Пожалуйста, введите действительный адрес электронной почты.',
    requestPrepared: 'Ваш запрос на доступ подготовлен. Пожалуйста, отправьте email, который только что открылся в вашем почтовом клиенте.',
    emailErrorPrefix: 'Не удалось открыть почтовый клиент. Пожалуйста, свяжитесь с ',
    emailErrorSuffix: ' вручную.',
    mailSubject: 'Запрос доступа к приложению',
    mailGreeting: 'Здравствуйте,',
    mailBody1: 'Я хотел бы получить доступ к приложению.',
    mailMyEmail: 'Мой адрес электронной почты:',
    mailMessage: 'Сообщение:',
    mailNoMessage: 'Нет дополнительного сообщения',
    mailThanks: 'Благодарю за рассмотрение моей заявки.',
    mailRegards: 'С уважением',
  },
  ja: {
    restrictedAccess: 'アクセス制限',
    enterEmail: 'メールアドレスを入力',
    verify: '確認',
    accessDenied: 'アクセス拒否：未認証または期限切れのメールアドレスです。',
    noAccess: 'まだアクセス権がありませんか？',
    requestAccess: 'アクセスを申請する',
    managementTitle: 'ユーザーアクセス管理',
    gsheetInfo: 'アクセスはGoogle Sheetsで管理されています。シートに直接メールを追加・削除してください — 変更はアプリの次回読み込み時に反映されます。',
    openGsheet: 'Google Sheetを開く',
    authorizedUsers: '認証済みユーザー',
    colEmail: 'メール',
    colValidUntil: '有効期限',
    colSource: 'ソース',
    srcPermanent: '永続',
    srcGsheet: 'Google Sheet',
    srcTemporary: '一時的',
    close: '閉じる',
    requestTitle: 'アクセスを申請する',
    requestDesc: 'このフォームに記入してアプリケーションへのアクセスを申請してください。管理者へのメールが自動的に準備されます。',
    yourEmail: 'メールアドレス *',
    emailPlaceholder: 'your.email@example.com',
    messageLabel: 'メッセージ（任意）',
    messagePlaceholder: 'アクセス申請の理由を入力してください...',
    cancel: 'キャンセル',
    send: '申請を送信',
    validEmail: '有効なメールアドレスを入力してください。',
    requestPrepared: 'アクセス申請が準備されました。メールクライアントで開いたメールを送信してください。',
    emailErrorPrefix: 'メールクライアントを開けませんでした。',
    emailErrorSuffix: 'に直接お問い合わせください。',
    mailSubject: 'アプリケーションへのアクセス申請',
    mailGreeting: 'こんにちは、',
    mailBody1: 'アプリケーションへのアクセスを希望しております。',
    mailMyEmail: '私のメールアドレス：',
    mailMessage: 'メッセージ：',
    mailNoMessage: '追加メッセージなし',
    mailThanks: '申請をご検討いただきありがとうございます。',
    mailRegards: 'よろしくお願いいたします',
  },
  zh: {
    restrictedAccess: '访问受限',
    enterEmail: '输入您的邮箱',
    verify: '验证',
    accessDenied: '访问被拒绝：邮箱地址未授权或已过期。',
    noAccess: '还没有访问权限？',
    requestAccess: '申请访问',
    managementTitle: '用户访问管理',
    gsheetInfo: '访问权限通过 Google Sheets 管理。直接在表格中添加或删除邮箱 — 下次加载应用时更改生效。',
    openGsheet: '打开 Google Sheet',
    authorizedUsers: '授权用户',
    colEmail: '邮箱',
    colValidUntil: '有效期至',
    colSource: '来源',
    srcPermanent: '永久',
    srcGsheet: 'Google Sheet',
    srcTemporary: '临时',
    close: '关闭',
    requestTitle: '申请访问',
    requestDesc: '填写此表单以申请应用程序访问权限。系统将自动为管理员准备一封邮件。',
    yourEmail: '您的邮箱地址 *',
    emailPlaceholder: 'your.email@example.com',
    messageLabel: '消息（可选）',
    messagePlaceholder: '请说明您申请访问的原因...',
    cancel: '取消',
    send: '发送申请',
    validEmail: '请输入有效的邮箱地址。',
    requestPrepared: '您的访问申请已准备好。请发送刚刚在您的邮件客户端中打开的邮件。',
    emailErrorPrefix: '无法打开您的邮件客户端。请手动联系 ',
    emailErrorSuffix: '。',
    mailSubject: '应用程序访问申请',
    mailGreeting: '您好，',
    mailBody1: '我希望申请访问该应用程序。',
    mailMyEmail: '我的邮箱地址：',
    mailMessage: '消息：',
    mailNoMessage: '无附加消息',
    mailThanks: '感谢您考虑我的申请。',
    mailRegards: '此致',
  },
};

export const getAuthTranslations = (langCode = 'fr') => {
  return authTranslations[langCode] || authTranslations.fr;
};
