// Traductions du nouvel onglet 4_QUENCH_Design1_ML (calcul Pyrofluid).
// fr + en fournis ; les autres langues retombent sur fr via la logique t()
// du composant (à fusionner dans QUENCH_traduction.jsx si préféré).
export const qdTranslations = {
  fr: {
    QD_legend_input: 'saisie',
    QD_legend_calc: 'calculé',
    QD_legend_warn: 'hors plage',
    QD_reload_from_flow: 'Recharger depuis le flux amont',

    QD_err_ts: "Impossible de trouver la température de saturation dans [40 °C ; min(T−1 ; 99,5) °C] : vérifier l'humidité et la température d'entrée.",
    QD_err_composition: 'Composition invalide : débits volumiques nuls ou débit HCl nul (le calcul du quench exige HCl > 0).',
    QD_warn_venturi: "L'efficacité d'absorption du venturi doit être comprise entre 0,5 et 0,7.",
    QD_warn_gouttes: 'Le diamètre des gouttes pulvérisées doit être compris entre 700 et 800 µm.',
    QD_warn_vitesse_colonne: 'Vitesse de passage colonne hors plage :',
    QD_warn_vitesse_cone: 'Vitesse de passage au cône hors plage :',
    QD_warn_recirc: "Débit de recirculation négatif : l'arrosage plafonné est insuffisant pour ce bilan",
    QD_warn_convergence: 'Boucle Ts / T sortie non convergée au critère de 0,5 °C (critère élargi, valeurs indicatives).',

    QD_section_entree: "Fumées en entrée",
    QD_section_sortie: 'Fumées en sortie',
    QD_section_bilans: 'Bilans eau & recirculation',

    QD_flow_CO2: 'Débit CO₂ [kg/h]',
    QD_flow_H2O: 'Débit H₂O vapeur [kg/h]',
    QD_flow_N2: 'Débit N₂ [kg/h]',
    QD_flow_O2: 'Débit O₂ [kg/h]',
    QD_flow_SO2: 'Débit SO₂ [kg/h]',
    QD_flow_HCl: 'Débit HCl [kg/h]',
    QD_temperature: 'Température [°C]',
    QD_depression: 'Dépression totale [mmCE]',

    QD_debit_massique_total: 'Débit massique total',
    QD_debit_volumique_total: 'Débit volumique total',
    QD_hcl_sec: 'HCl (sec, 11 % O₂)',
    QD_so2_sec: 'SO₂ (sec, 11 % O₂)',
    QD_hcl_kg: 'Débit HCl',
    QD_vitesse_colonne: 'Vitesse de passage colonne (10–15)',
    QD_vitesse_cone: 'Vitesse de passage au cône (30–40)',

    QD_ts: 'Température de saturation Ts',
    QD_eau_evaporee: 'Eau de saturation (évaporée)',
    QD_zsat: 'Hauteur de saturation Zsat',
    QD_diam_cone_retenu: 'Diamètre du cône retenu',
    QD_pventuri: 'Perte de charge venturi',
    QD_mol_incond: "Débit molaire d'incondensables",
    QD_temps_evap: "Temps d'évaporation des gouttes",

    QD_temp_sortie: 'Température de sortie',
    QD_eff_hcl: 'Efficacité HCl',
    QD_ro_epuree: 'ρ fumées épurées (réel)',

    QD_appoint: "Débit eau d'appoint",
    QD_arrosage: "Débit du liquide d'arrosage",
    QD_recirc: 'Débit eau de recirculation',
    QD_purge: 'Débit purge',
    QD_conc_hcl_rec: 'Conc. HCl recirculation',
    QD_conc_hcl_ar: 'Conc. HCl arrosage',
    QD_ph_arrosage: "pH eau d'arrosage",
    QD_ph_recirc: 'pH recirculation',

    QD_cone_saisi: 'Diamètre du cône saisi (sinon table standard)',
    QD_diam_cone: 'Diamètre du cône [mm]',
    QD_temp_eau_appoint: "Température eau d'appoint [°C]",
    QD_eff_venturi: "Efficacité d'absorption du venturi",
    QD_diam_gouttes: 'Diamètre des gouttes pulvérisées [µm]',
    QD_const_nusselt: 'Constante de Nusselt',
    QD_coef_haut_sat: 'Coef. hauteur saturation',
    QD_use_pventuri: 'PDC = ΔP venturi calculée',

    // Rapport
    QD_report_section: 'Dimensionnement du quench (voie humide)',
    QD_report_saturation: 'Saturation',
    QD_report_sortie: 'Fumées en sortie',
    QD_report_bilans: 'Bilans eau',
  },
  en: {
    QD_legend_input: 'input',
    QD_legend_calc: 'calculated',
    QD_legend_warn: 'out of range',
    QD_reload_from_flow: 'Reload from upstream flow',

    QD_err_ts: 'Cannot find saturation temperature within [40 °C ; min(T−1 ; 99.5) °C]: check moisture and inlet temperature.',
    QD_err_composition: 'Invalid composition: zero volume flows or zero HCl flow (the quench calculation requires HCl > 0).',
    QD_warn_venturi: 'Venturi absorption efficiency must be between 0.5 and 0.7.',
    QD_warn_gouttes: 'Sprayed droplet diameter must be between 700 and 800 µm.',
    QD_warn_vitesse_colonne: 'Column velocity out of range:',
    QD_warn_vitesse_cone: 'Cone velocity out of range:',
    QD_warn_recirc: 'Negative recirculation flow: capped spray flow is insufficient for this balance',
    QD_warn_convergence: 'Ts / outlet-T loop not converged at 0.5 °C criterion (widened criterion, indicative values).',

    QD_section_entree: 'Inlet flue gas',
    QD_section_sortie: 'Outlet flue gas',
    QD_section_bilans: 'Water & recirculation balances',

    QD_flow_CO2: 'CO₂ flow [kg/h]',
    QD_flow_H2O: 'H₂O vapour flow [kg/h]',
    QD_flow_N2: 'N₂ flow [kg/h]',
    QD_flow_O2: 'O₂ flow [kg/h]',
    QD_flow_SO2: 'SO₂ flow [kg/h]',
    QD_flow_HCl: 'HCl flow [kg/h]',
    QD_temperature: 'Temperature [°C]',
    QD_depression: 'Total draft [mmWC]',

    QD_debit_massique_total: 'Total mass flow',
    QD_debit_volumique_total: 'Total volume flow',
    QD_hcl_sec: 'HCl (dry, 11 % O₂)',
    QD_so2_sec: 'SO₂ (dry, 11 % O₂)',
    QD_hcl_kg: 'HCl flow',
    QD_vitesse_colonne: 'Column velocity (10–15)',
    QD_vitesse_cone: 'Cone velocity (30–40)',

    QD_ts: 'Saturation temperature Ts',
    QD_eau_evaporee: 'Saturation water (evaporated)',
    QD_zsat: 'Saturation height Zsat',
    QD_diam_cone_retenu: 'Selected cone diameter',
    QD_pventuri: 'Venturi pressure drop',
    QD_mol_incond: 'Incondensable molar flow',
    QD_temps_evap: 'Droplet evaporation time',

    QD_temp_sortie: 'Outlet temperature',
    QD_eff_hcl: 'HCl efficiency',
    QD_ro_epuree: 'Cleaned gas density (actual)',

    QD_appoint: 'Make-up water flow',
    QD_arrosage: 'Spray liquid flow',
    QD_recirc: 'Recirculation water flow',
    QD_purge: 'Blowdown flow',
    QD_conc_hcl_rec: 'HCl conc. recirculation',
    QD_conc_hcl_ar: 'HCl conc. spray',
    QD_ph_arrosage: 'Spray water pH',
    QD_ph_recirc: 'Recirculation pH',

    QD_cone_saisi: 'Manual cone diameter (else standard table)',
    QD_diam_cone: 'Cone diameter [mm]',
    QD_temp_eau_appoint: 'Make-up water temperature [°C]',
    QD_eff_venturi: 'Venturi absorption efficiency',
    QD_diam_gouttes: 'Sprayed droplet diameter [µm]',
    QD_const_nusselt: 'Nusselt constant',
    QD_coef_haut_sat: 'Saturation height coef.',
    QD_use_pventuri: 'PDC = calculated venturi ΔP',

    // Report
    QD_report_section: 'Quench design (wet route)',
    QD_report_saturation: 'Saturation',
    QD_report_sortie: 'Outlet flue gas',
    QD_report_bilans: 'Water balances',
  },
};
